services:
  web:
    build: ./build/
    container_name: order-management-web
    working_dir: /src
    restart: always
    tty: true
    ports:
      - 80:80
    volumes:
      - ./src:/src
  db:
    image: mysql
    container_name: order-management-db
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./var:/var/lib/mysql